name: ci

on:
  pull_request:
    branches:
      - main

jobs:

  ci:
    name: ci
    runs-on: ubuntu-latest
    steps:
      - name: checkout repositry
        uses: actions/checkout@v4

      - name: setup environment of Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.4'

      - name: format src
        run: test -z $(gofmt -l .)

      - name: static analysis
        run: go vet ./...

      - name: test
        run: go test

      - name: build
        run: go build .
