name: release

on:
  push:
    branches:
      - main

jobs:

  build:
    name: build
    runs-on: ubuntu-latest

    steps:
      - name: checkout repositry
        uses: actions/checkout@v4

      - name: setup environment of Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.4'

      - name: build
        run: go build .

      - name: upload artifact file
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: ./actions_hanson

  deploy:
    name: deploy 
    runs-on: ubuntu-latest
    needs: build

    permissions:
      contents: write 

    steps:

      - uses: actions/checkout@v4
      - name: dwonload artifact file
        uses: actions/download-artifact@v4
        with:
          name: build
          path: ./actions_hanson

      - name: show directory
        run: ls ./

      - name: deploy to Github Release
        run: gh release upload v1.0.0 ./actions_hanson
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

